#!/bin/bash
#I ideally would've used two different hook scripts for both of my webservers, but since our accounts are private I just wget the hooky one from yor Project 2 folder.
#So in order to automate adding the hook script to post-receive it will output the same echo for both. 
TARGET="/var/www/html/"
GIT_DIR="/home/ubuntu/mastersite1"
BRANCH="master"

echo "Kicking off post-receive from 10.0.0.20 - Apache1"
while read oldrev newrev ref
do
        # only checking out the master (or whatever branch you would like to deploy)
        if [ "$ref" = "refs/heads/$BRANCH" ];
        then
                echo "Ref $ref received. Deploying ${BRANCH} branch to production..."
                git --work-tree=$TARGET --git-dir=$GIT_DIR checkout -f $BRANCH
        else
                echo "Ref $ref received. Doing nothing: only the ${BRANCH} branch may be deployed on this server."
        fi
done
